# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
baseurl: ""
title                    : "Cheng Wu | Data Science at Columbia University"
description              : ""
repository               : "ChengWu-Data/chengwu-data.github.io"
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      :  # get google_analytics_id from https://analytics.google.com/analytics/

# SEO Related
google_site_verification :  "googleba9a1384104a9b43"
bing_site_verification   :  # get bing_site_verification from https://www.bing.com/webmasters/about
baidu_site_verification  :  # get baidu_site_verification from https://ziyuan.baidu.com/login/index?u=/site/index

# Site Author
author:
  name             : "Cheng Wu"
  avatar           : "/images/avatar.png"
  bio              : "Columbia Engineering"
  location         : "NY, USA"
  employer         :
  pubmed           : 
  googlescholar    : 
  email            : "cheng.w@columbia.edu"
  researchgate     :  # e.g., "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "ChengWu-Data"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : # e.g., "https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : "cheng-wu-1ab27922a"
  dblp             : # e.g., "https://dblp.org/pid/xx/xxxx.html"
  orcid            : # e.g., "https://orcid.org/xxxx"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


# 中文作者信息
author_zh:
  name             : "吴骋"
  avatar           : "/images/avatar.png"
  bio              : "哥伦比亚大学工程学院"
  location         : "纽约，美国"
  email            : "cheng.w@columbia.edu"
  github           : "ChengWu-Data"
  linkedin         : "cheng-wu-1ab27922a"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
timezone: Asia/Shanghai # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
