title: "Zhuoka Feng"
description: ""
url: "https://arkazhuo.github.io"
baseurl: ""
repository: "ArkaZhuo/ArkaZhuo.github.io"

google_scholar_stats_use_cdn: true

author:
  name: "Zhuoka Feng"
  bio: "School of Computer Science, Fudan University"
  email: "23307130211@m.fudan.edu.cn"
  avatar: "images/profile1.jpg"
  location: "Shanghai, China"
  github: "ArkaZhuo"
  googlescholar: "https://scholar.google.com/citations?user=C_Oh2igAAAAJ&hl=en&oi=ao"

exclude:
  - README.md
  - docs/
