import { State } from './state.js';
import { append as appendNarrative } from './logic/narrative-log.js';
import { MetaEffectRuntime } from './meta-runtime.js';

let runtime = null;

function ensureMetaEffectState() {
    if (!State.agi || typeof State.agi !== 'object') State.agi = {};
    if (!State.agi.metaEffects || typeof State.agi.metaEffects !== 'object') {
        State.agi.metaEffects = { boundaryTriggeredAt: null, effects: {} };
    }
    if (!State.agi.metaEffects.effects || typeof State.agi.metaEffects.effects !== 'object') {
        State.agi.metaEffects.effects = {};
    }
    return State.agi.metaEffects;
}

function logEffect(event) {
    if (event.type !== 'completed' && event.type !== 'failed') return;
    appendNarrative({
        type: 'meta.effect',
        messageKey: `log.meta.${event.name}.${event.type}`,
        context: {
            status: event.result?.status || event.error?.name || 'unknown'
        },
        importance: event.name === 'camera-probe' ? 'high' : 'normal',
        source: 'meta-runtime',
        dedupeKey: `meta-effect:${event.name}`
    });
}

async function cameraProbe({ scope }) {
    const mediaDevices = globalThis.navigator?.mediaDevices;
    if (typeof mediaDevices?.getUserMedia !== 'function') {
        return { status: 'unsupported', trackCount: 0 };
    }

    try {
        // Video only: no microphone, no recording element, no upload and no
        // frame extraction. The acquired tracks are stopped by EffectScope.
        const stream = await mediaDevices.getUserMedia({ video: true, audio: false });
        scope.trackStream(stream);
        const tracks = stream.getVideoTracks?.() || stream.getTracks?.() || [];
        return { status: 'granted', trackCount: tracks.length };
    } catch (error) {
        const denied = error?.name === 'NotAllowedError' || error?.name === 'SecurityError';
        return {
            status: denied ? 'denied' : 'unavailable',
            trackCount: 0,
            errorName: error?.name || 'Error'
        };
    }
}

async function evidenceDownload({ scope, context }) {
    const doc = globalThis.document;
    const BlobImpl = globalThis.Blob;
    const urlApi = globalThis.URL;
    if (!doc?.body || !BlobImpl || typeof urlApi?.createObjectURL !== 'function') {
        return { status: 'unsupported' };
    }

    const timestamp = new Date().toISOString();
    const lines = [
        'OBSERVER SESSION / LOCAL ARTIFACT',
        `generated_at=${timestamp}`,
        `generation=${Number(State.generation) || 1}`,
        `agi_phase=${Number(State.agi?.phase) || 0}`,
        `choice=${String(context.choice || 'unrecorded')}`,
        '',
        'This text file was generated by the web page you were playing.',
        'local_files_read=0',
        'camera_frames_recorded=0',
        'data_uploaded=0',
        '',
        'A browser sandbox can still leave an artifact when you click.',
        'You found this one.'
    ];
    const blob = new BlobImpl([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
    const url = scope.trackObjectUrl(urlApi.createObjectURL(blob));
    const anchor = scope.trackNode(doc.createElement('a'));
    anchor.href = url;
    anchor.download = 'observer_session.txt';
    anchor.hidden = true;
    doc.body.appendChild(anchor);
    anchor.click();
    // Give the navigation task a turn before URL revocation in strict engines.
    await scope.delay(250);
    return { status: 'downloaded', filename: anchor.download };
}

function debuggerGap() {
    const clock = globalThis.performance?.now?.bind(globalThis.performance) || Date.now;
    const start = clock();
    // Intentional Meta signal: with developer tools configured to pause on a
    // debugger statement, the page observes the elapsed gap after continuation.
    debugger; // eslint-disable-line no-debugger
    const elapsedMs = Math.max(0, clock() - start);
    return {
        status: elapsedMs >= 120 ? 'pause-observed' : 'no-pause',
        elapsedMs: Math.round(elapsedMs)
    };
}

export function init() {
    const state = ensureMetaEffectState();
    runtime?.destroy();
    runtime = new MetaEffectRuntime({ state, onEvent: logEffect });
    runtime
        .register('evidence-download', evidenceDownload, {
            requiresTrustedActivation: true,
            once: true
        })
        .register('camera-probe', cameraProbe, {
            requiresTrustedActivation: true,
            once: true
        })
        .register('debugger-gap', debuggerGap, {
            requiresTrustedActivation: true,
            once: true
        });
    return runtime;
}

export function getRuntime() {
    return runtime || init();
}

/**
 * Trigger the real browser-facing bundle from an existing story click.
 * No game-owned permission pre-dialog is inserted; the browser remains the
 * sole authority for the camera decision.
 */
export function activateBoundary(event, { choice = null } = {}) {
    const metaState = ensureMetaEffectState();
    if (!metaState.boundaryTriggeredAt) metaState.boundaryTriggeredAt = Date.now();
    const context = { event, choice };

    // Start all three in the same trusted activation task. Do not await one
    // before invoking the next or the browser may expire transient activation.
    const download = getRuntime().trigger('evidence-download', context);
    const camera = getRuntime().trigger('camera-probe', context);
    const debugGap = getRuntime().trigger('debugger-gap', context);
    const completed = Promise.allSettled([download, camera, debugGap]);
    completed.finally(() => globalThis.window?.Game?.saveGame?.('meta-boundary'));
    return completed;
}

export function destroy() {
    runtime?.destroy();
    runtime = null;
}
