name: Get Citation Data

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install Reqs
      run: |
        python -m pip install --upgrade pip
    - name: Run
      run: |
        cd ./google_scholar_crawler
        pip install -r requirements.txt
        python main.py
        cd ./results
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git add *.json
        if git diff --cached --quiet; then
          echo "No citation changes to commit"
        else
          git commit -m "Updated Citation Data"
          git push "${remote_repo}" HEAD:google-scholar-stats --force
        fi
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
